import { useRouter } from "next/router";
import Head from "next/head";

import AppFooter from "../components/AppFooter";
import AppBackground from "@/components/AppBackground";
import AppMenu from "@/components/AppMenu";

import { NotificationContextProvider } from "@/store/notification-context";

import "../styles/app.scss";
import "../styles/app-assistant.scss";

function WhiteLionApp({ Component, pageProps }) {
  const router = useRouter();

  const isTourPage = router.pathname === "/tour";

  return (
    <NotificationContextProvider>
      {/*  Head */}
      <Head>
        <title>White Lion - AI Solutions</title>

        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no"
          name="viewport"
        />

        <link
          rel="stylesheet"
          href="https://cdn.materialdesignicons.com/5.4.55/css/materialdesignicons.min.css"
        />
      </Head>

      {/* Background effect */}
      {!isTourPage && <AppBackground />}

      {/* Body */}
      <div
        className={
          "rounded-xl text-center main-box " + (!isTourPage ? "mt-9" : "")
        }
      >
        {/* Main Menu */}
        {!isTourPage && <AppMenu />}

        {/* Dynamic Body */}
        <Component key="body" {...pageProps} />
      </div>

      {/* // Footer */}
      {!isTourPage && <AppFooter />}
    </NotificationContextProvider>
  );
}

export default WhiteLionApp;
